---
version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:13
    env_file:
      - .env
    environment:
      PGUSER: ${POSTGRESQL_USER}
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root"]
      timeout: 45s
      interval: 10s
      retries: 10
    ports:
      - "5432:5432"
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    restart: always

volumes:
  postgres-db-volume:
